# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo Pet App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo Pet App

pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SimpleKeychain', '~> 1.0'
pod 'SDWebImage'

  target 'Demo Pet AppTests' do
    inherit! :search_paths
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
  end

  target 'Demo Pet AppUITests' do
    # Pods for testing
  end

end
